---
title: "Computação em R: estatística experimental"
author: "Eric Bastos Gorgens & Marcio Leles Romarco de Oliveira"
date: "1/17/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sumário

[Sobre o livro](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/00-Intro.html)

[1. Delineamentos experimentais](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/01-Delineamentos.html)

[2. Pressuposições e transformações](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/02-Pressuposicoes.html)

[3. ANOVA no R](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/03-AnovaR.html)

[4. Investigando os dados](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/04-Investigando.html)

[5. Delineamento inteiramente casualizado](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/05-dic.html)

[6. Delineamento em blocos casualizados](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/06-dbc.html)

[7. Fatorial duplo inteiramente casualizado](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/07-fatorialDic.html)

[8. Fatorial duplo em blocos casualizados](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/08-fatorialDbc.html)

[9. Parcela subdividida](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/09-parcelaSub.html)

[10. Análise não paramétrica](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/10-naoParametrica.html)

[11. Proximos passos](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/11-nextSteps.html)

## Sobre o livro

[Webpage version](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/00-Intro.html)

Bem-vindo ao mundo do R. O R não é só um software, nem se resume a uma linguagem. O R é um estilo de pesquisar, estudar e ensinar. Através de seus códigos e scripts você entrará num mundo sem limites, aberto à experimentação e à troca de experiência. Um mundo em que não existe apenas uma forma de se chegar à resposta correta, mas sim uma gama de alternativas! Você deve estar se perguntando: porque começar a trabalhar com o R? A resposta passa por algumas perspectivas interessantes.

R é gratuito. Por se tratar de um projeto de código aberto, você pode usar o R sem nenhum custo adicional: ou seja sem necessidade de pagar por inscrições, assinaturas, licenças ou limitações. Sendo o R aberto, você pode ter acesso ao código e ajustá-lo às suas necessidades (para mais detalhes veja: GNU General Public License version 2). Centenas de experts ao redor do mundo fazem exatamente isto e suas contribuições beneficiam milhares de usuários do R.

R é uma linguagem. No R, você realiza uma análise escrevendo funções e scripts; e não clicando em botões na tela. Isto pode assustar e parecer difícil, mas na verdade, a linguagem R é uma linguagem simples de aprender e muito natural para análise de dados. Aprender uma linguagem tem vários benefícios. Por se tratar de uma linguagem interativa, o R promove uma oportunidade de experimentar e explorar os dados de forma profunda e detalhada. Um script documenta passo a passo da análise, do acesso aos dados até os resultados das análises, podendo ser executados a qualquer momento, por qualquer pessoa.
Gráficos e visualização de dados. Faz parte das premissas de criações do R, a certeza de que a visualização dos dados através de gráficos é uma parte essencial de qualquer análise dos dados. Como resultado, o R oferece excelentes ferramentas para criação de gráficos, de barras até multi-painéis. Os recursos gráficos do R é influenciado pelos principais pensadores da área de visualização de dados como Bill Cleveland e Edward Tufte. Gráficos do R podem ser vistos em respeitadas publicações mundiais como The New York Times, The Economist, e o blog FlowingData.

Pacote flexível de análises estatísticas. Você irá encontrar no R um conjunto de ferramentas prontamente disponíveis, desde o acesso à vários tipos de dados, até recursos para manipulação de dados, passando pelos modelos estatísticos tradicionais e modernos. Todos os recursos estão disponíveis numa plataforma orientada a objeto que torna fácil a programação e construção de relatórios.

Acesso às poderosas e avançadas técnicas estatísticas. Os principais acadêmicos e pesquisadores do mundo utilizam o R para desenvolver as novidades nas áreas de estatística, máquinas de aprendizado e modelagem. Você pode encontrar extensões para o R contendo desenvolvimento de ponta na área econômica, genética e muitos outros campos. Atualmente são mais de 2000 pacotes que incrementam o seu R disponíveis para download.

Uma brilhante e vibrante comunidade. Com centenas de contribuidores e mais de dois milhões de usuários ao redor do mundo, se você tiver uma dúvida sobre o R, as chances de alguém já ter esbarrada com este problema é muito grande. A comunidade é gigante e participativa. A mediana de tempo que uma pergunta leva para ser respondida no StackOverflow (maior comunidade de programadores do mundo) é de 0.0147 dias, o que equivale a 21 minutos.

O R é multiplataforma rodando em Linux, Mac ou Windows. Ainda é possível configurar para rodar diretamente da nuvem. O R valoriza o que a empresa tem de mais valioso: você!
Possibilidades infinitas. Com o R você não está limitado por uma sequência pré-definida de rotinas. Você pode usar todo o portfólio de códigos e soluções disponíveis na comunidade ou mesmo criar suas próprias funções. É possível inclusive combinar o R com outros recursos como uma base de dados MySQL, ou um Apache web-server, ou ainda com o Google Maps API. Qual a sua ideia?

[Próximo capítulo](https://htmlpreview.github.io/?https://github.com/Gorgens/compR/blob/master/020_experimental/01-Delineamentos.html)
